version: "3"
services:

  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:alpine-trunk
    container_name: zabbix-server-mysql
    env_file:
      - .env_db_mysql
      - .env_srv
    ports:
      - 10051:10051
    links:
      - mysql-server:mysql-server
      - zabbix-java-gateway:zabbix-java-gateway
    depends_on:
      - mysql-server
      - zabbix-java-gateway
      - zabbix-snmptraps
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro 
      - /data/zabbix/zabbix_server/alertscripts:/usr/lib/zabbix/alertscripts
      - /data/zabbix/zabbix_server/externalscripts:/usr/lib/zabbix/externalscripts
      - /data/zabbix/snmptraps:/var/lib/zabbix/snmptraps:rw
    stop_grace_period: 30s
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.all.secure_redirects=0
      - net.ipv4.conf.all.send_redirects=0
  #  devices:
  #   - "/dev/ttyUSB0:/dev/ttyUSB0" 
    labels:
      com.zabbix.description: "Zabbix server with MySQL database support"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-server"
      com.zabbix.dbtype: "mysql"
      com.zabbix.os: "alpine"      

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-trunk
    container_name: zabbix-web
    env_file:
      - .env_db_mysql
      - .env_web
    ports:
      - 80:8080
      - 8443:8443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro 
      - /data/zabbix/zabbix_web/zbx_env/etc/ssl/nginx:/etc/ssl/nginx:ro
      - /data/zabbix/zabbix_web/zbx_env/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
      - ./.SIMYOU.TTF:/usr/share/zabbix/assets/fonts/DejaVuSans.ttf
    links:
      - mysql-server:mysql
      - zabbix-server-mysql:zabbix-server
    depends_on:
      - mysql-server
      - zabbix-server-mysql
    sysctls:
      - net.core.somaxconn=65535
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 3
      #start_period: 30s
    labels:
      com.zabbix.description: "Zabbix frontend on Nginx web-server with MySQL database support"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-frontend"
      com.zabbix.webserver: "nginx"
      com.zabbix.dbtype: "mysql"
      com.zabbix.os: "alpine"

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-trunk
    container_name: zabbix-agent
    env_file:
    - .env_agent
    ports:
      - "10050:10050"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/zabbix/zabbix_agent/zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
      - /data/zabbix/zabbix_agent/zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - /data/zabbix/zabbix_agent/zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - /data/zabbix/zabbix_agent/zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
    links:
    - zabbix-server-mysql:zabbix-server
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
      mode: global
    privileged: true
    pid: "host"
    stop_grace_period: 5s
    labels:
      com.zabbix.description: "Zabbix agent"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-agentd"
      com.zabbix.os: "alpine"

  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:alpine-trunk
    container_name: zabbix-java-gateway
    ports:
      - "10052:10052"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    env_file:
      - .env_java
    stop_grace_period: 5s
    labels:
      com.zabbix.description: "Zabbix Java Gateway"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "java-gateway"
      com.zabbix.os: "alpine"

  zabbix-snmptraps:
    image: zabbix/zabbix-snmptraps:alpine-trunk
    container_name: zabbix-snmptraps
    ports:
      - "162:1162/udp"
    volumes:
      - /data/zabbix/snmptraps:/var/lib/zabbix/snmptraps
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    stop_grace_period: 5s
    labels:
      com.zabbix.description: "Zabbix snmptraps"
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "snmptraps"
      com.zabbix.os: "alpine"
  
  mysql-server:
    image: mysql:5.6
    container_name: mysql-server
    env_file:
      - .env_db_mysql
    ports:
      - 3306:3306
    volumes:
      - /data/zabbix/mysql:/var/lib/mysql
    command: 
      --character-set-server=utf8
      --collation-server=utf8_bin
